# coding: utf-8

# flake8: noqa
"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

# import models into model package
from openapi_client.models.detail import Detail
from openapi_client.models.error_response import ErrorResponse
from openapi_client.models.model import Model
from openapi_client.models.model_response import ModelResponse
