openapi: 3.0.2
info:
  title: FastAPI
  version: 0.1.0
servers:
- url: /
paths:
  /api/models:
    get:
      operationId: getModels_api_models_get
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Response_Getmodels_Api_Models_Get'
          description: Successful Response
      security:
      - APIKeyHeader: []
      summary: Getmodels
components:
  schemas:
    Detail:
      properties:
        message:
          title: Message
          type: string
        type:
          title: Type
          type: string
        param:
          title: Param
        code:
          title: Code
          type: string
      required:
      - code
      - message
      - type
      title: Detail
      type: object
    ErrorResponse:
      properties:
        detail:
          $ref: '#/components/schemas/Detail'
      required:
      - detail
      title: ErrorResponse
      type: object
    Model:
      properties:
        slug:
          title: Slug
          type: string
        max_tokens:
          title: Max Tokens
          type: integer
        title:
          title: Title
          type: string
        description:
          title: Description
          type: string
        tags:
          items: {}
          title: Tags
          type: array
      required:
      - description
      - max_tokens
      - slug
      - tags
      - title
      title: Model
      type: object
    ModelResponse:
      properties:
        models:
          items:
            $ref: '#/components/schemas/Model'
          title: Models
          type: array
      title: ModelResponse
      type: object
    Response_Getmodels_Api_Models_Get:
      anyOf:
      - $ref: '#/components/schemas/ErrorResponse'
      - $ref: '#/components/schemas/ModelResponse'
      title: Response Getmodels Api Models Get
  securitySchemes:
    APIKeyHeader:
      in: header
      name: token
      type: apiKey
