/*
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.client.model.Detail;
import org.openapitools.client.model.ErrorResponse;
import org.openapitools.client.model.Model;
import org.openapitools.client.model.ModelResponse;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for ResponseGetmodelsApiModelsGet
 */
public class ResponseGetmodelsApiModelsGetTest {
    private final ResponseGetmodelsApiModelsGet model = new ResponseGetmodelsApiModelsGet();

    /**
     * Model tests for ResponseGetmodelsApiModelsGet
     */
    @Test
    public void testResponseGetmodelsApiModelsGet() {
        // TODO: test ResponseGetmodelsApiModelsGet
    }

    /**
     * Test the property 'detail'
     */
    @Test
    public void detailTest() {
        // TODO: test detail
    }

    /**
     * Test the property 'models'
     */
    @Test
    public void modelsTest() {
        // TODO: test models
    }

}
